### ISSUE TITLE
Update investmentRegister to pass array instead of JSON

### ISSUE THREAD

**Issue by ijazulrehman** [ninetydays/kross-SDK#102]
Currently, the post investments endpoint only accepts a JSON object with the properties 'amount' and 'loan_id' . This limits the ability to make a single investment since it requires passing a JSON object. To make it more flexible, we are updating the endpoint to accept an array instead of JSON in this [PR](https://github.com/ninetydays/olive/pull/159).

The updated endpoint would take an array of objects with the same properties 'amount' and 'loan_id'. To make a single investment, the client would need to pass an array with a single element.

Kindly up[date the following changes to the investmentRegister function in the FE app:

javascript
```
investmentRegister({ amount, loan_id }: InvestmentRegisterDto) {
  return this.instance.post<InvestmentRegisterResponse>('/investments', [{
    amount,
    loan_id,
  }]);
}
```
With this change, the endpoint will be able to accept an array of investments instead of a single JSON object. This will make the endpoint more flexible and easier to use.

**Comment by aziyatali** [comment]
@ijazulrehman  makes sense. 
However, olive side has not been merged right?
