### ISSUE TITLE
InvestmentLimit issue corporate

### ISSUE THREAD

**Issue by aziyatali** [ninetydays/kross-SDK#158]
issue: Equal distribute fails for corporates.
reason: investmentAmountLimit from investmentLimit function return zero(0) as kftcInvestmentLimit is zero for corporates.
Fix: for corporates, we should get rid of kftcLimit.

Original code: 
**Corporate user:**
```
const investmentAmountLimit = Math.min(
              availableAmountToWithdrawInAccount,
              kftcInvestmentLimit < 0
                ? availableAmountToWithdrawInAccount
                : kftcInvestmentLimit 
            );
```
kftcInvestmentLimit in above code which comes from kftc endpoint is always zero.

if user is corporate then will change as below:

```
const investmentAmountLimit = Math.min(
              availableAmountToWithdrawInAccount,
              isCorporate 
                ? availableAmountToWithdrawInAccount
                : kftcInvestmentLimit 
            );

```

cc: @JonghunYu @Jscripter-pk

**Comment by aziyatali** [comment]
@Jscripter-pk  What was the reason to implement this particular case:
```
 kftcInvestmentLimit < 0
                ? availableAmountToWithdrawInAccount
                : kftcInvestmentLimit 
```
When kftcInvestmentLimit might be less than zero?

**Comment by Jscripter-pk** [comment]
@aziyatali there was a special edge-case that @JonghunYu let me to handle here 
```const kftcInvestmentLimit =
              kftcInvestInquiry?.data?.code === 'A8151'
                ? -1
                : (kftcInvestInquiry?.data?.data?.limit || 0) -
                  (kftcInvestInquiry?.data?.data?.balance || 0);
```
kftcInvestInquiry?.data?.code === 'A8151' => -1

**Comment by aziyatali** [comment]
@Jscripter-pk  Ah, It seems `kftcInvestInquiry?.data?.data?.code` lol.

**Comment by Jscripter-pk** [comment]
@aziyatali ah then it might be because of this

**Comment by aziyatali** [comment]
@Jscripter-pk  Yeah, now distributing the loans to corporate working fine.

**Comment by Jscripter-pk** [comment]
@aziyatali sexy
