### ISSUE TITLE
productListNew 

### ISSUE THREAD

**Issue by aziyatali** [ninetydays/kross-SDK#28]
Add productListNew function implemented on top of the loans and investments. We get loans where state is pending or funding and show whether current user has invested, the amount etc. It will be shown on loans page & details in investor app

**Comment by JonghunYu** [comment]
I would name it just loans instead of following old function name

**Comment by aziyatali** [comment]
@JonghunYu  Got it! I will come up with better naming

**Comment by JonghunYu** [comment]
And i don't think we should create a function by the state of the loan but create one generic function and pass state as a query parameter as we implemented in the backend

**Comment by aziyatali** [comment]
@JonghunYu We already have implemented loans in the kross-sdk as loanData. What I am going to do is create a generic function and pass state as query parameter now.

**Comment by Jscripter-pk** [comment]
@aziyatali Yes I think we should keep the loans function as I have already updated instead of adding state and stuff.
User of the sdk will decide based on filter they will decide which loans are needed by them
