### ISSUE TITLE
Handle defaults/response format for totalAssets

### ISSUE THREAD

**Issue by Jscripter-pk** [ninetydays/kross-SDK#64]
When we navigate to Mypage totalAssets data which you are showing in graph returning error. Please have a look and fix the issue.

**Comment by aziyatali** [comment]
@Jscripter-pk  Is this still the case?

**Comment by Jscripter-pk** [comment]
No but one thing I see from mobile side is that it show NaN for percentage on top of graph which I think should be handled from mobile side rather than sdk

**Comment by Jscripter-pk** [comment]
https://user-images.githubusercontent.com/36015615/222098137-93512781-b863-4288-8ca0-f7a0f4bc3b83.mov

@aziyatali yes I am using latest 40x version of sdk

**Comment by aziyatali** [comment]
@Jscripter-pk Isn't it showing cos data is not yet being fetched from kross-sdk! It should be handled in client side.(app)

**Comment by Jscripter-pk** [comment]
@aziyatali I think so but showing user Nan doesn't make sense. instead show a better number or state for that if data is not fetched yet

**Comment by aziyatali** [comment]
@Jscripter-pk  growthRate initially set to 0 till it gets fetched. Umm, weird. I will look into it

**Comment by Jscripter-pk** [comment]
yeah check maybe you are doing some calculation which is leading to that error. maybe zero division or related
